"""Report Engine – generates security assessment reports in multiple formats."""

import json
import os
import time
from datetime import datetime
from typing import Optional

from portal.config import REPORTS_DIR


class ReportEngine:

    def __init__(self):
        REPORTS_DIR.mkdir(exist_ok=True)

    def generate_markdown(self, scan_data: dict) -> str:
        pkg = scan_data.get("package", "Unknown")
        summary = scan_data.get("summary", {})
        sev = summary.get("severity_counts", {})
        ts = scan_data.get("timestamp", time.time())
        dt = datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")

        md = f"""# Android Security Assessment Report

## Target Application
- **Package:** `{pkg}`
- **Scan Date:** {dt}
- **Duration:** {scan_data.get('duration', 0):.1f}s
- **Scanner:** AndroidINONE Portal

---

## Executive Summary

| Metric | Value |
|--------|-------|
| **Risk Level** | {summary.get('risk_level', 'N/A')} |
| **Risk Score** | {summary.get('risk_score', 0)} |
| **Total Findings** | {summary.get('total_findings', 0)} |
| Critical | {sev.get('CRITICAL', 0)} |
| High | {sev.get('HIGH', 0)} |
| Medium | {sev.get('MEDIUM', 0)} |
| Low | {sev.get('LOW', 0)} |
| Info | {sev.get('INFO', 0)} |

---

## Device Information

"""
        dev = scan_data.get("device_info", {})
        for k, v in dev.items():
            md += f"- **{k.replace('_', ' ').title()}:** {v}\n"

        md += "\n---\n\n## Package Information\n\n"
        pkg_info = scan_data.get("package_info", {})
        for k in ["package_name", "version_name", "version_code", "target_sdk", "min_sdk", "is_debuggable"]:
            if k in pkg_info:
                md += f"- **{k.replace('_', ' ').title()}:** {pkg_info[k]}\n"

        for section, key in [
            ("Static Analysis Findings", "static_findings"),
            ("Dynamic Analysis Findings", "dynamic_findings"),
            ("Network Findings", "network_findings"),
            ("Component Findings", "component_findings"),
        ]:
            findings = scan_data.get(key, [])
            if not findings:
                continue

            md += f"\n---\n\n## {section} ({len(findings)})\n\n"

            by_severity = {"CRITICAL": [], "HIGH": [], "MEDIUM": [], "LOW": [], "INFO": []}
            for f in findings:
                by_severity.setdefault(f.get("severity", "INFO"), []).append(f)

            for sev_name in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
                items = by_severity.get(sev_name, [])
                if not items:
                    continue
                md += f"\n### {sev_name} ({len(items)})\n\n"
                for i, f in enumerate(items, 1):
                    md += f"#### {i}. {f.get('title', 'Untitled')}\n\n"
                    md += f"- **Category:** {f.get('category', 'N/A')}\n"
                    md += f"- **Location:** {f.get('location', 'N/A')}\n"
                    if f.get('description'):
                        md += f"- **Description:** {f['description']}\n"
                    if f.get('evidence'):
                        md += f"- **Evidence:** `{f['evidence'][:200]}`\n"
                    if f.get('recommendation'):
                        md += f"- **Recommendation:** {f['recommendation']}\n"
                    md += "\n"

        cats = summary.get("category_counts", {})
        if cats:
            md += "\n---\n\n## Findings by Category\n\n"
            md += "| Category | Count |\n|----------|-------|\n"
            for cat, cnt in sorted(cats.items(), key=lambda x: -x[1]):
                md += f"| {cat} | {cnt} |\n"

        md += f"""
---

## Recommendations

1. **Remediate CRITICAL findings immediately** – These represent direct security vulnerabilities.
2. **Address HIGH findings** in the next sprint – They can be exploited with moderate effort.
3. **Plan MEDIUM fixes** – These increase the attack surface.
4. **Review LOW/INFO** – For security hardening and best practices.

---

## Methodology

This assessment was performed using AndroidINONE Portal with the following techniques:
- **Static Analysis:** APK manifest parsing, DEX string scanning, secrets detection, semgrep MASVS rules
- **Dynamic Analysis:** Runtime inspection via Frida, SharedPreferences audit, database enumeration
- **Component Testing:** Exported component enumeration, ContentProvider probing, Intent fuzzing
- **Network Analysis:** Traffic interception capability, cleartext detection, certificate analysis
- **Agent Integration:** drozer assessment framework, Medusa dynamic hooks, OWASP Mobile Top 10 checks

---

*Generated by AndroidINONE Portal – {dt}*
"""
        return md

    def generate_json(self, scan_data: dict) -> str:
        return json.dumps(scan_data, indent=2, default=str)

    def generate_html(self, scan_data: dict) -> str:
        import html as h
        pkg = scan_data.get("package", "Unknown")
        summary = scan_data.get("summary", {})
        sev = summary.get("severity_counts", {})
        ts = scan_data.get("timestamp", time.time())
        dt = datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")
        dev = scan_data.get("device_info", {})
        pkg_info = scan_data.get("package_info", {})

        sev_colors = {
            "CRITICAL": ("#ff1744", "#2d0a0a"),
            "HIGH": ("#ff5722", "#2d1a0a"),
            "MEDIUM": ("#ff9800", "#2d2200"),
            "LOW": ("#06b6d4", "#0a2025"),
            "INFO": ("#2196f3", "#0a1525"),
        }

        findings_html = ""
        for section_name, key in [
            ("Static Analysis", "static_findings"),
            ("Dynamic Analysis", "dynamic_findings"),
            ("Network", "network_findings"),
            ("Component", "component_findings"),
        ]:
            items = scan_data.get(key, [])
            if not items:
                continue
            findings_html += f'<h2>{section_name} ({len(items)})</h2>'
            for f in items:
                sev_name = f.get("severity", "INFO")
                color, bg = sev_colors.get(sev_name, ("#999", "#222"))
                findings_html += f'''
                <div style="border:1px solid #30363d;border-left:3px solid {color};border-radius:6px;padding:12px;margin:8px 0;background:{bg}">
                    <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px">
                        <span style="background:{color};color:#fff;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:bold">{sev_name}</span>
                        <strong>{h.escape(f.get("title", ""))}</strong>
                    </div>
                    <div style="font-size:13px;color:#8b949e;margin-bottom:4px">{h.escape(f.get("category", ""))} &middot; {h.escape(f.get("location", ""))}</div>
                    {f'<div style="font-size:13px;margin:4px 0">{h.escape(f.get("description", ""))}</div>' if f.get("description") else ''}
                    {f'<div style="background:#161b22;padding:6px 10px;border-radius:4px;font-family:monospace;font-size:12px;margin:4px 0;color:#ff7b72">{h.escape(str(f.get("evidence", ""))[:200])}</div>' if f.get("evidence") else ''}
                    {f'<div style="color:#3fb950;font-size:12px;margin-top:4px">Recommendation: {h.escape(f.get("recommendation", ""))}</div>' if f.get("recommendation") else ''}
                </div>'''

        cats = summary.get("category_counts", {})
        cats_html = ""
        if cats:
            cats_html = '<h2>Findings by Category</h2><table><tr><th>Category</th><th>Count</th></tr>'
            for cat, cnt in sorted(cats.items(), key=lambda x: -x[1]):
                cats_html += f"<tr><td>{h.escape(cat)}</td><td>{cnt}</td></tr>"
            cats_html += "</table>"

        return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>Security Report - {h.escape(pkg)}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:'Segoe UI',-apple-system,sans-serif;background:#0a0e17;color:#c9d1d9;line-height:1.6;padding:0}}
.container{{max-width:960px;margin:0 auto;padding:24px}}
h1{{color:#58a6ff;font-size:24px;border-bottom:2px solid #1f6feb;padding-bottom:12px;margin-bottom:20px}}
h2{{color:#58a6ff;font-size:18px;margin:24px 0 12px;padding-bottom:6px;border-bottom:1px solid #21262d}}
table{{border-collapse:collapse;width:100%;margin:10px 0}}
th,td{{border:1px solid #21262d;padding:8px 12px;text-align:left;font-size:13px}}
th{{background:#161b22;color:#58a6ff;font-weight:600}}
tr:nth-child(even){{background:#0d1117}}
code{{background:#161b22;padding:1px 5px;border-radius:3px;color:#ff7b72;font-size:12px}}
.header{{background:linear-gradient(135deg,#0d1117,#161b22);padding:24px;border-radius:10px;border:1px solid #21262d;margin-bottom:20px}}
.grid5{{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:16px 0}}
.scard{{background:#161b22;border-radius:8px;padding:14px;text-align:center;border:1px solid #21262d}}
.scard .n{{font-size:28px;font-weight:bold}}
.scard .l{{font-size:12px;color:#8b949e;margin-top:2px}}
.meta-grid{{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:16px 0}}
.meta-card{{background:#161b22;border-radius:8px;padding:14px;border:1px solid #21262d}}
.meta-card h3{{font-size:14px;color:#d2a8ff;margin-bottom:8px}}
.footer{{text-align:center;padding:20px;color:#484f58;font-size:12px;border-top:1px solid #21262d;margin-top:30px}}
</style></head><body>
<div class="container">
<div class="header">
<h1>Android Security Assessment Report</h1>
<table style="border:none"><tr style="background:none">
<td style="border:none;color:#8b949e">Package</td><td style="border:none"><strong><code>{h.escape(pkg)}</code></strong></td>
<td style="border:none;color:#8b949e">Date</td><td style="border:none"><strong>{dt}</strong></td>
<td style="border:none;color:#8b949e">Risk</td><td style="border:none"><strong style="color:{'#ff1744' if summary.get('risk_level')=='CRITICAL' else '#ff9800'}">{h.escape(str(summary.get('risk_level', 'N/A')))}</strong></td>
</tr></table>
</div>

<div class="grid5">
<div class="scard"><div class="n" style="color:#ff1744">{sev.get('CRITICAL',0)}</div><div class="l">Critical</div></div>
<div class="scard"><div class="n" style="color:#ff5722">{sev.get('HIGH',0)}</div><div class="l">High</div></div>
<div class="scard"><div class="n" style="color:#ff9800">{sev.get('MEDIUM',0)}</div><div class="l">Medium</div></div>
<div class="scard"><div class="n" style="color:#06b6d4">{sev.get('LOW',0)}</div><div class="l">Low</div></div>
<div class="scard"><div class="n" style="color:#2196f3">{sev.get('INFO',0)}</div><div class="l">Info</div></div>
</div>

<div class="meta-grid">
<div class="meta-card"><h3>Device</h3><table>{''.join(f"<tr><td style='color:#8b949e;width:100px'>{h.escape(k)}</td><td>{h.escape(str(v))}</td></tr>" for k,v in dev.items() if v)}</table></div>
<div class="meta-card"><h3>Package</h3><table>{''.join(f"<tr><td style='color:#8b949e;width:100px'>{h.escape(k)}</td><td>{h.escape(str(v))}</td></tr>" for k,v in pkg_info.items() if v)}</table></div>
</div>

{findings_html}
{cats_html}

<h2>Recommendations</h2>
<ol style="padding-left:20px;font-size:13px">
<li><strong style="color:#ff1744">Remediate CRITICAL findings immediately</strong> – direct security vulnerabilities</li>
<li><strong style="color:#ff5722">Address HIGH findings in the next sprint</strong> – exploitable with moderate effort</li>
<li><strong style="color:#ff9800">Plan MEDIUM fixes</strong> – increase attack surface</li>
<li><strong style="color:#06b6d4">Review LOW/INFO</strong> – hardening and best practices</li>
</ol>

<div class="footer">Generated by AndroidINONE Portal &middot; {dt}</div>
</div></body></html>"""

    def save_report(self, scan_data: dict, fmt: str = "json") -> str:
        scan_id = scan_data.get("scan_id", str(int(time.time())))
        pkg = scan_data.get("package", "unknown")

        generators = {
            "json": (self.generate_json, ".json"),
            "markdown": (self.generate_markdown, ".md"),
            "html": (self.generate_html, ".html"),
        }

        gen, ext = generators.get(fmt, generators["json"])
        content = gen(scan_data)

        filename = f"report_{pkg}_{scan_id}{ext}"
        filepath = REPORTS_DIR / filename

        with open(filepath, "w") as f:
            f.write(content)

        return str(filepath)

    def list_reports(self) -> list[dict]:
        reports = []
        if not REPORTS_DIR.exists():
            return reports
        for f in REPORTS_DIR.iterdir():
            if f.suffix in (".json", ".md", ".html") and f.name.startswith("report_"):
                reports.append({
                    "filename": f.name,
                    "path": str(f),
                    "size": f.stat().st_size,
                    "created": f.stat().st_ctime,
                    "format": f.suffix.lstrip("."),
                })
        return sorted(reports, key=lambda x: x["created"], reverse=True)
